### ISSUE TITLE
Nps output bug

### ISSUE THREAD

**Issue by rwbc** [codeandkey/neocortex#4] opened 2020-09-02 08:47 UTC
Hi Justin,

By accident I stumbled again over neocortex, but unlike last time it could be build here :)
I noticed some glitch though in the output and nps went negative in depth 7.
(this was on a very old core2 machine and not yet optimized compile, so no need to worry about
probably low nps)

Guenther

```

uci
uciok
id name neocortex 1.0
id author Justin Stanley
ucinewgame
go infinite
2020-09-02 10:40:45 INFO     > snapshot [rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1]:
            | white | black |
------------|-------|-------|
material_mg |  3900 |  3900 |
material_eg |  4300 |  4300 |
attackbonus |    46 |    44 |
mobility_mg |    64 |    64 |
mobility_eg |    76 |    76 |
ctr_control |     0 |     0 |
king_safety |   110 |   110 |
blocked_pns |     0 |     0 |
passed_pns  |     0 |     0 |
adv_pawn_mg |    32 |    32 |
adv_pawn_eg |    64 |    64 |
adv_psd_mg  |     0 |     0 |
adv_psd_eg  |     0 |     0 |
adv_king_mg |     0 |     0 |
adv_king_eg |     0 |     0 |
phase       |           243 |
info depth 0 nodes 1 score cp 12
info depth 1 nodes 41 score cp 81 pv d2d4
info depth 2 nodes 138 time 1 nps 69000 score cp 12 pv d2d4 d7d5
info depth 3 nodes 2352 time 4 nps 470400 score cp 80 pv e2e3 b8c6 d1g4
info depth 4 nodes 14947 time 23 nps 597880 score cp 3 pv b1c3 e7e6 d2d4 d8g5
info depth 5 nodes 130517 time 202 nps 639789 score cp 74 pv b1c3 b8c6 e2e3 d7d5 d1g4
info depth 6 nodes 1163740 time 2141 nps 543042 score cp 3 pv b1c3 e7e6 e2e3 d8g5 d1f3 b8c6
info depth 7 nodes 7789227 time 13818 nps -57938 score cp 50 pv g1f3 g8f6 b1c3 b8c6 d2d4 d7d5 d1d3
```

**Comment by codeandkey** [comment] 2020-09-04 18:22
Hi Guenther!

Thanks very much for finding this bug and contributing to neocortex :)
The bug was caused by an overflow in the nps calculation and will be fixed with #6.

Justin

**Comment by rwbc** [comment] 2020-09-06 09:22
> 
> 
> Hi Guenther!
> 
> Thanks very much for finding this bug and contributing to neocortex :)
> The bug was caused by an overflow in the nps calculation and will be fixed with #6.
> 
> Justin

Hi again Justin,

JFYI I have added a few compilations for download at my site. (this was still with the nps overflow)
https://rwbc-chess.de/download.htm
At least one of the CCRL testers is currently running tests with it.
http://talkchess.com/forum3/viewtopic.php?f=2&t=72613&start=360#p859232
http://ccrl.chessdom.com/

Any idea when you will add an official relase or binaries? (I wouldn't mind adding my compilations for download for now.)
I will update my compilations with the fix probably today or tomorrow.
(It will make no difference for strength anyway, as it is purely cosmetical)

**Comment by rwbc** [comment] 2020-09-06 10:36
I recompiled it with the 'fix', but there is another issue in calculation not only an overflow.
The calculation is simply wrong from depth 7 onwards.

**Edit:** depth 1 seems also off by factor 2

Haven't looked at the source yet, but do you do some recalculations of time and/or not using
the reported time variable from the uci output for nps? (or roundings)

```
w/o rounding
depth 6 => 7780407/12,537=620595
depth 7 => 57841570/103,693=557815
```


```
uci
uciok
id name neocortex 1.0
id author Justin Stanley
ucinewgame
isready
readyok
go infinite
2020-09-06 12:05:52 INFO     > snapshot [rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1]:
            | white | black |
------------|-------|-------|
material_mg |  3900 |  3900 |
material_eg |  4300 |  4300 |
attackbonus |    46 |    44 |
mobility_mg |    64 |    64 |
mobility_eg |    76 |    76 |
ctr_control |     0 |     0 |
king_safety |   110 |   110 |
blocked_pns |     0 |     0 |
passed_pns  |     0 |     0 |
adv_pawn_mg |    32 |    32 |
adv_pawn_eg |    64 |    64 |
adv_psd_mg  |     0 |     0 |
adv_psd_eg  |     0 |     0 |
adv_king_mg |     0 |     0 |
adv_king_eg |     0 |     0 |
phase       |           243 |
info depth 0 nodes 1 score cp 12
info depth 1 nodes 41 score cp 81 pv d2d4
info depth 2 nodes 138 time 1 nps 69000 score cp 12 pv d2d4 d7d5
info depth 3 nodes 2352 time 3 nps 470400 score cp 80 pv e2e3 b8c6 d1g4
info depth 4 nodes 14947 time 22 nps 649869 score cp 3 pv b1c3 e7e6 d2d4 d8g5
info depth 5 nodes 130517 time 189 nps 686931 score cp 74 pv b1c3 b8c6 e2e3 d7d5 d1g4
info depth 6 nodes 1163740 time 1970 nps 590431 score cp 3 pv b1c3 e7e6 e2e3 d8g5 d1f3 b8c6
info depth 7 nodes 7780407 time 12537 nps 277990 score cp 50 pv g1f3 g8f6 b1c3 b8c6 d2d4 d7d5 d1d3
info depth 8 nodes 57841570 time 103693 nps 19354 score cp 10 pv g1f3 g8f6 b1c3 b8c6 d2d4 d7d5 d1d3 d8d6
```

**Comment by codeandkey** [comment] 2020-09-06 21:02
Hi Guenther!

I looked at this again and pushed some more changes which should hopefully fix the problem. I'll reopen this issue in the meantime.

The time was being measured separately for time and nps, so it's been changed to a single sample.
And for the nps I changed the calculation to just use floating point arithmetic instead of casting, the output seems to be correct now. 

Thanks for posting neocortex to the talkchess board! I'm glad people are interested.

My mistake for not including binaries with the last release, I will be sure to do that in 1.1 which will come soon. I have some new features in progress which should significantly improve strength.

**Comment by rwbc** [comment] 2020-09-07 11:28
Thanks for the quick fix Justin!
All ok now. I have updated the binaries at my site.
You can close this issue now.

BTW if you still don't know yet, below is my XB/UCI chronology, where you can find also fitting opponent engines for future tests :-)
https://rwbc-chess.de/chronology.htm (this is the overview, there is also a full details version link there, or at my main site)

I guess though that the goal of your engine probably was being a sparring partner for a wide range of weaker or average Humans at lichess.

**Comment by codeandkey** [comment] 2020-09-07 21:02
Good to hear! And thanks very much for the resource; I will definitely check out those engines.
As neocortex is the first engine I've built it was not intended to compete with strong engines, yet ;)

**Closed as completed by codeandkey** 2020-09-07 21:02 UTC
Labels: bug
